/* 
[
    "4746741644200012",
    "A. Rivai",
    "196304142000121001",
    "Guru Mapel",
    "Kepala Perpustakaan",
    "IV/a",
    "JL.BERINGIN PSR VII  G.MERPATI",
    '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/1 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
]
**/
const teachers = [
    [
        "4746741644200012",
        "A. Rivai",
        "196304142000121001",
        "Guru Mapel",
        "Kepala Perpustakaan",
        "IV/a",
        "JL.BERINGIN PSR VII  G.MERPATI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/1 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "8650766668130102",
        "Abdul Manan Tamba",
        "-",
        "Guru Mapel",
        "-",
        "",
        "DUSUN TANI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/2 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2843747649200032",
        "Adirianto",
        "196905112005021001",
        "Guru Mapel",
        "Kepala Program Keahlian",
        "IV/a",
        "DUSUN PONDOK 13 KAMPUNG SAWIT SEBERANG",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/3 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4953751653200022",
        "Albret Juniamanson Purba",
        "197306211999031003",
        "Guru Mapel",
        "Kepala Unit Produksi",
        "IV/b",
        "LING. V BERINGIN BLOK A NO 85 STABAT",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/4 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "7533748650200023",
        "Alfin Fitriawan",
        "197012012005021001",
        "Guru Mapel",
        "Kepala Program Keahlian",
        "IV/a",
        "JL. KARYA BAKTI LING. 1",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/5 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "5160739640200023",
        "Aman Tampubolon",
        "196108281990031005",
        "Guru Mapel",
        "-",
        "IV/b",
        "SIMPANG PADANG LANGKAT DESA AIR HITAM GEBANG",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/6 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "7143755656300043",
        "Amunah",
        "197708112014072004",
        "Guru Mapel",
        "-",
        "III/a",
        "Jl. R. Suprapto No 28",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/7 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "7834760661300052",
        "Anggeriani Tanjung",
        "198205022006042011",
        "Guru Mapel",
        "-",
        "IV/a",
        "S. PARMAN GG SEJAHTERA",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/8 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0645743644200042",
        "Anggiat",
        "196503132007011005",
        "Guru Mapel",
        "Kepala Program Keahlian",
        "III/c",
        "Jl. Penguin IX No. 433",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/9 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2838748651200022",
        "Armensyah",
        "197005062008011002",
        "Guru Mapel",
        "-",
        "III/d",
        "Dusun V Psr.1 Hilir",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/10 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2159767668300013",
        "Asmiatus Sakinah",
        "-",
        "Guru BK",
        "-",
        "",
        "DUSUN IV PASAR VI ARA CONDONG",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/11 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2641746648200032",
        "Aswad",
        "196803092007011003",
        "Guru Mapel",
        "-",
        "III/c",
        "JL. T.A. HAMZAH NO 73",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/12 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "8653743646200032",
        "Berita Sembiring",
        "196503212006041001",
        "Guru Mapel",
        "-",
        "III/d",
        "JL. MEDAN - BINJAI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/13 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4039744646300063",
        "Cahaya Lasma Lumban Tobing",
        "196607072000122002",
        "Guru Mapel",
        "-",
        "IV/b",
        "JL. PELITA I",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/14 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3935754656300022",
        "Chairiah",
        "197606032006042004",
        "Guru Mapel",
        "Kepala Bengkel",
        "IV/a",
        "BINJAI TANJUNG PURA KM 29,5 NO 82",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/15 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4633770671130012",
        "Dely Kurnia Putri Harahap",
        "-",
        "Guru Mapel",
        "-",
        "",
        "JL. KARYA IV Gg. PEMUDA NO. 177",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/16 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "9457756658300012",
        "Demi Anita",
        "197801252014072003",
        "Guru Mapel",
        "-",
        "III/b",
        "JL. JEND. SUDIRMAN NO. 62 LK.V",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/17 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0055748650200033",
        "Derman Lingga",
        "197007231999031005",
        "Guru Mapel",
        "-",
        "IV/a",
        "JL. SUTOYO",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/18 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4744739640200042",
        "Desmon Simangunsong",
        "196104121999031001",
        "Guru Mapel",
        "-",
        "IV/b",
        "JL. BAKTI LUHUR GG. SUPLIR NO.78B MEDAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/19 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0039759661300023",
        "Dewi Gusti",
        "198107072009042004",
        "Guru Mapel",
        "-",
        "III/c",
        "Jl. Kol. M. HAIYAR NO.23",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/20 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "5047764665110043",
        "Dhimas Prayogi",
        "198607152011011018",
        "Guru Mapel",
        "Pembina OSIS",
        "III/b",
        "JL. ALBADAR VII LK. II",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/21 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Dody Satria Permadi, S.pd",
        "-",
        "Guru Mapel",
        "-",
        "",
        "JL. SEROJA 44",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/22 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "6542742644200043",
        "Eddy Prianto",
        "196412101988031007",
        "Guru Mapel",
        "-",
        "IV/b",
        "Jl. Jamin Ginting Lk.1 No. 22-D",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/23 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Edi Syahputra",
        "-",
        "Guru Mapel",
        "-",
        "",
        "Dusun I Jawa",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/24 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3548752654300053",
        "Elida Turnip",
        "197412162014072001",
        "Guru BK",
        "-",
        "III/a",
        "JL. R. SUPRAPTO LINGK. VIII",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/25 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3541750652300072",
        "Eni Yuniati",
        "197202092008012001",
        "Guru Mapel",
        "-",
        "III/d",
        "JL DANAU BARATAN 1 NO 67 C",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/26 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "6352746648300043",
        "Erni Suryani",
        "196810202005022001",
        "Guru Mapel",
        "Kepala Program Keahlian",
        "IV/a",
        "MEDAN DUA",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/27 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "9556771671130022",
        "Fery Hamdani",
        "-",
        "Guru Mapel",
        "-",
        "",
        "JL. KARYA BAKHTI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/28 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "8662737640300002",
        "Halimah Tunsakdiah",
        "195903301981032003",
        "Guru Mapel",
        "-",
        "IV/b",
        "JLN. S. PARMAN LK VIII BANTENAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/29 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2741732643300002",
        "Helmi. S",
        "196404091994121001",
        "Guru Mapel",
        "Kepala Bengkel",
        "IV/b",
        "JL. GATOT SUBROTO KM 8,2 NO 309 C",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/30 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "1833760662200042",
        "Hermanto",
        "198205012009041006",
        "Guru Mapel",
        "-",
        "III/c",
        "Dusun III Jati Rejo Pasar 6 Kw. Mencirim",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/31 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "7662767668200012",
        "Heru Ramadhani",
        "-",
        "Guru Mapel",
        "-",
        "",
        "BARU JAYA",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/32 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "9139744647200053",
        "Hoddy Marisi Batubara",
        "196608071993031005",
        "Guru Mapel",
        "-",
        "IV/b",
        "JL. SUDIRMAN PERDAMAIAN STABAT",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/33 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4061743644200013",
        "Hudri Nasution",
        "196507291992031007",
        "Guru Mapel",
        "Koordinator Bursa Kerja Khusus SMK",
        "IV/b",
        "JL. BAKTI LUHUR GG KUDA LAUT NO 171 MEDAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/34 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3439758660200042",
        "Ibrahim",
        "-",
        "Guru Mapel",
        "-",
        "",
        "Jl. Kota Rantang Ds.IV",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/35 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0254740641110003",
        "Ilyas",
        "196209221983021004",
        "Kepala Sekolah",
        "Kepala Sekolah",
        "IV/b",
        "TANJUNG PURA",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/36 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3847749651300042",
        "Ipun Suharti",
        "197105152008012004",
        "Guru Mapel",
        "-",
        "III/d",
        "JL. GARU LK. IV",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/37 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "5846763664300092",
        "Irma Sofiya",
        "-",
        "Guru Mapel",
        "-",
        "",
        "TANJUNG PURA",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/38 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4760748649300022",
        "Irnawaty Tanjung.spd",
        "197004282000122002",
        "Guru Mapel",
        "-",
        "IV/b",
        "JL. IKAN SENANGIN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/39 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "1046747649200023",
        "Izkariman",
        "-",
        "Guru Mapel",
        "-",
        "",
        "JL. S. PARMAN NO 66",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/40 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3958746651200002",
        "Jaidun Turnip",
        "196806262005021001",
        "Guru Mapel",
        "Wakil Kepala Sekolah Kurikulum",
        "IV/a",
        "LINGK. V BERINGIN BLOK B",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/41 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "8160755657200013",
        "Jepri Herayudi",
        "197708282008011004",
        "Guru Mapel",
        "Pembina Pramuka Putra",
        "III/b",
        "Jl. T. AMIR HAMZAH",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/42 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "5542748650200032",
        "Jisman Sirait",
        "197002102000121001",
        "Guru Mapel",
        "-",
        "IV/a",
        "JL. MURNI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/43 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2052751653300073",
        "Juliana",
        "197307202010012004",
        "Guru Mapel",
        "Kepala Program Keahlian",
        "III/c",
        "JL. BAKTI ABRI DUSUN IV",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/44 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0537758660200023",
        "Jumadi",
        "-",
        "Guru Mapel",
        "-",
        "",
        "JL. KHAIRIL ANWAR NO. 31 TG. PURA",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/45 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2949749651200052",
        "Junaidi",
        "197106112008011001",
        "Guru TIK",
        "Kepala Program Keahlian",
        "III/d",
        "JL. DANAU BARATAN 1 NO.67C",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/46 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "8944749652200022",
        "Junaidi",
        "197106122008011002",
        "Guru Mapel",
        "-",
        "III/c",
        "Jl. Suka Mulia",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/47 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "5952747649200032",
        "Juni Siswanto",
        "196906202006041004",
        "Guru Mapel",
        "-",
        "IV/a",
        "JL. PITURAH GG. PELITA",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/48 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "KHAIRUN NISA NIZANUDIN",
        "-",
        "Guru Mapel",
        "-",
        "",
        "Jln. Perjuangan No. 24",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/49 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3462749650200012",
        "Kristince Tambunan",
        "197101301999032001",
        "Guru Mapel",
        "-",
        "IV/b",
        "JL. LADA 3 NO. 18 P. SIMALINGKAR",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/50 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2544746649300052",
        "Lidia Br Sihole",
        "196802122000122002",
        "Guru Mapel",
        "-",
        "IV/b",
        "JL. T. UMAR NO. 65 BINJAI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/51 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "7958740643300002",
        "Lindawati Marpaung",
        "196206261990032004",
        "Guru Mapel",
        "-",
        "IV/a",
        "L. KAWAT III NO 75 TG. MULIA MEDAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/52 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "9543738640300073",
        "Lisken Siahaan",
        "196012112014072001",
        "Guru Mapel",
        "-",
        "III/a",
        "JL. KELAPA SAWIT",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/53 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "5838749651200032",
        "Manimbul Harianja",
        "197105061997021002",
        "Guru Mapel",
        "Wakil Kepala Sekolah Humas",
        "IV/b",
        "Perumnas Langkat Berseri B. 14 Stabat",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/54 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "1343748655200003",
        "Marudut Tua Sihole",
        "197010112007011004",
        "Guru Mapel",
        "-",
        "III/c",
        "JL. TEUKU UMAR NO. 65 LK.6",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/55 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0949738641200032",
        "Masang Tuah",
        "196006171993121001",
        "Guru Mapel",
        "-",
        "IV/a",
        "DUSUN IX PASAR BESAR NO 48",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/56 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "8137755656200013",
        "Mashuri",
        "197708052008011003",
        "Guru Mapel",
        "-",
        "III/d",
        "LING. V SEI DENDANG",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/57 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0340750653200013",
        "Masrianto",
        "197210082008011001",
        "Guru Mapel",
        "-",
        "III/c",
        "LING. V SEI DENDANG",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/58 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "9535769670130072",
        "Maulana Erwin Saputra",
        "-",
        "Guru TIK",
        "-",
        "",
        "DSN IV Budi Utomo",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/59 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "9863748650300012",
        "Mei Yusni Gultom",
        "197005312005022001",
        "Guru Mapel",
        "-",
        "IV/a",
        "JL. BROMO Lr. SEDERHANA NO. 1 MEDAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/60 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "MELLA PUSPITA SARI",
        "-",
        "Guru Mapel",
        "-",
        "",
        "JLN. SEPAKAT LINGK. VI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/61 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Mhd. Basri Daulay",
        "-",
        "Guru Mapel",
        "-",
        "",
        "JL. P. KEMERDEKAAN NO. 105. LK. VI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/62 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4849745647200052",
        "Misno",
        "196705171990031004",
        "Guru Mapel",
        "-",
        "IV/a",
        "DUSUN BERINGIN BLOK C 14 PERDAMAIAN STABAT",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/63 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "6143740642300063",
        "Morina",
        "196208111988032003",
        "Guru Mapel",
        "-",
        "IV/b",
        "JL. PENERANGAN STABAT",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/64 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2448751652200012",
        "Muhammad Azhar Ariawan",
        "197301161999031002",
        "Guru Mapel",
        "Wakil Kepala Sekolah Kesiswaan",
        "IV/b",
        "JL. ANGGREK  LINK. I",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/65 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0337769671130053",
        "Muhammad Ilham",
        "-",
        "Guru BK",
        "-",
        "",
        "LING. X DUSUN PURWOSARI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/66 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "5734754655200012",
        "Muhammad Zulham",
        "197604022008011003",
        "Guru Mapel",
        "Kepala Bengkel",
        "III/c",
        "PERUMAHAN PONDOK NUSANTARA BLI 1 NO. 17",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/67 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "6040757660200013",
        "Mujiono",
        "197907082005021002",
        "Guru Mapel",
        "Pembina Pramuka Putri",
        "IV/a",
        "DUSUN PAYA RENGO",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/68 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "5835769670130042",
        "Nanda Sanjani",
        "-",
        "Guru BK",
        "-",
        "",
        "PAYA KANGKUNG",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/69 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "6945752653300022",
        "Nurbaiti",
        "197406131999032004",
        "Guru Mapel",
        "Kepala Laboratorium",
        "IV/b",
        "JLN.JEND.SUDIRMAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/70 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "1544743646300103",
        "Nursiah",
        "196512121990032006",
        "Guru Mapel",
        "-",
        "IV/a",
        "JL. KELAPA SAWIT C.10D",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/71 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4549747649300043",
        "Pardamean Natalina",
        "196912172005022001",
        "Guru Mapel",
        "-",
        "IV/a",
        "Jl. TALAM I LK VI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/72 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "6433749652200042",
        "Parno",
        "197101012000121002",
        "Guru Mapel",
        "Kepala Program Keahlian",
        "IV/b",
        "JLN.JEND. SUDIRMAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/73 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3651742644200022",
        "Pudjiantoro",
        "196403191992031002",
        "Guru Mapel",
        "Kepala Bengkel",
        "IV/b",
        "BLOK R 3 TAMAN KW DAMAI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/74 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2139751652300043",
        "Puji Agustina",
        "197208072005022001",
        "Guru Mapel",
        "Kepala Bengkel",
        "III/d",
        "PERUMNAS KELAPA SAWIT, BLOK A 98",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/75 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0360742644200023",
        "Purwandi",
        "196410282006041001",
        "Guru Mapel",
        "-",
        "IV/a",
        "JL. SUTOYO",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/76 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "RATNA PERMATA SARI",
        "-",
        "Guru Mapel",
        "-",
        "",
        "JLN. P. KEMERDEKAAN LK. VI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/77 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2440750652200023",
        "Rayahman Raymulus Pasaribu",
        "197211081999031002",
        "Guru Mapel",
        "-",
        "IV/a",
        "PERINTIS BARU",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/78 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Rekha Razulla",
        "-",
        "Guru BK",
        "-",
        "",
        "Jln. S. Parman Lingk. VII",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/79 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "9652748649300012",
        "Rika Luckita Sari",
        "197003202005022001",
        "Guru Mapel",
        "-",
        "IV/a",
        "Jl. Rahmadsyah Gg. Setia No. 9/243 Medan",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/80 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "9557750652300082",
        "Rohana Manurung",
        "197202252000032003",
        "Guru Mapel",
        "-",
        "III/d",
        "stabat",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/81 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "8442741642300072",
        "Rosdewi Ani",
        "196301101999032003",
        "Guru Mapel",
        "-",
        "IV/b",
        "JL. PABRIK TENUN 105 MEDAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/82 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "7240741641300003",
        "Rosdiana Sitanggang",
        "196309081987032003",
        "Guru Mapel",
        "-",
        "IV/b",
        "JL. MURNI NO.9A STABAT",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/83 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Safiratur Raihan",
        "-",
        "Guru Kelas",
        "-",
        "",
        "PSR. I KP.DONDONG STABAT LAMA",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/84 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3748747648300002",
        "Samariahta Saragih",
        "196904162007012002",
        "Guru Mapel",
        "-",
        "III/d",
        "Jl. Raimuna 12 no.59 Berngam Binjai",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/85 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2445745648300023",
        "Sanin Wagiati",
        "196711132000122002",
        "Guru Mapel",
        "Kepala Bengkel",
        "IV/b",
        "TENGKU AMIR HAMZAH LINGK I BINJAI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/86 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "9357765666130083",
        "Sarah Marliessa Hutapea",
        "-",
        "Guru Mapel",
        "-",
        "",
        "Link I Karya",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/87 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3649751652300032",
        "Satriani Tisnawati",
        "197303172000122001",
        "Guru Mapel",
        "-",
        "IV/a",
        "Jl. KAPTEN MUSLIM Gg. RUKUN MAKMUR NO.3",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/88 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Selamet",
        "-",
        "Guru Mapel",
        "-",
        "",
        "Jl. Petrochina",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/89 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2251733635200013",
        "Semin",
        "195509191977021001",
        "Guru Mapel",
        "-",
        "IV/a",
        "PASAR 1 GOHOR LAMA",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/90 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "7537752654130093",
        "Siswany Debora Munthe",
        "-",
        "Guru Mapel",
        "-",
        "",
        "LK. V BERINGIN BLOK A 85",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/91 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2442760662300063",
        "Siti Hajar",
        "198211102014072005",
        "Guru Mapel",
        "-",
        "III/a",
        "KARANG REJO",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/92 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "1055746648300043",
        "Sri Erawati Lestyaningsih",
        "196807231999032002",
        "Guru Mapel",
        "-",
        "IV/a",
        "JL. SUTOYO LING. III SIDOMULYO STABAT",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/93 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3544753655300052",
        "Sri Minarti",
        "197502122006042006",
        "Guru Mapel",
        "Kepala Program Keahlian",
        "IV/a",
        "Jl. R. Suprapto Gg. Kurnia II Stabat",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/94 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "SRI NOVIANTI",
        "-",
        "Guru Mapel",
        "-",
        "",
        "LINK. VI HINAI KIRI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/95 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3548751652300002",
        "Sriani",
        "197302162005022004",
        "Guru Mapel",
        "-",
        "III/d",
        "JL. PANCING V NO. 46 LK. II",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/96 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "7555738640300023",
        "Sulasteri Simorangkir",
        "196012231987032006",
        "Guru Mapel",
        "-",
        "IV/b",
        "L. IKAN SENANGIN NO.9 TURIAM BINJAI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/97 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "1759758662200002",
        "Sulistiono",
        "198004272014071004",
        "Guru Mapel",
        "Kepala Program Keahlian",
        "III/b",
        "ASRAMA KEBUN LADA. NO.246",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/98 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0347753655200043",
        "Sumantri",
        "197510152008011001",
        "Guru Mapel",
        "-",
        "III/d",
        "JL.SEI BANGKATAN LK II",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/99 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0049749650200023",
        "Susana Santosa",
        "197107172005021001",
        "Guru Mapel",
        "Kepala Bengkel",
        "IV/a",
        "JL. UTAMA NO 4",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/100 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "7033741642200053",
        "Syarifuddin",
        "196307012006041002",
        "Guru Mapel",
        "Wakil Kepala Sekolah Sarpras",
        "IV/a",
        "jln. Besar stabat secanggang",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/101 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4744748650300102",
        "Syawaliah",
        "197004122007012007",
        "Guru Mapel",
        "-",
        "III/d",
        "Ling. III Sejahtera",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/102 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "5941746649300042",
        "Tengku Radiah",
        "196806092014072001",
        "Guru Mapel",
        "-",
        "III/b",
        "JL. MANGGA NO 7",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/103 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4163743644200013",
        "Tolhas Matondang",
        "196508311999031001",
        "Guru Mapel",
        "-",
        "IV/b",
        "Jl. Titipan Gg. Rezeki No. 50",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/104 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0551749650300022",
        "Umdhatus Salihat",
        "197102191999032003",
        "Guru Mapel",
        "-",
        "IV/b",
        "JL. PERNIAGAAN NO. 106",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/105 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "9154745648200023",
        "Wagimin",
        "196708221990031001",
        "Guru Mapel",
        "-",
        "IV/a",
        "BATU MELENGGANG",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/106 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "7557749652300033",
        "Wardaningsih",
        "197112251999032004",
        "Guru Mapel",
        "-",
        "IV/b",
        "DESA JENTERA STABAT",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/107 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "7047756656300003",
        "Yuli Haryati",
        "197807152005022001",
        "Guru Mapel",
        "-",
        "III/d",
        "JL. GATOT SUBROTO KM 8.2 NO. 309 C",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/108 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Yuliani Saragih",
        "-",
        "Guru Kelas",
        "-",
        "",
        "JL TITI PAPAN GG. PERSATUAN  15A",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/109 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0741743647200022",
        "Zulfikar",
        "196504091999031001",
        "Guru Mapel",
        "-",
        "IV/b",
        "Jl. Sentosa",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/110 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "1247743646200033",
        "Zulkarnain",
        "196509152007011002",
        "Guru Mapel",
        "Kepala Program Keahlian",
        "III/d",
        "JL. SATU NO. B33",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/111 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "3249756656200003",
        "Andri Idrus Kurniawan",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "JL. KARYA BAKTI LK. 1 STABAT",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/112 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Angga Pranoto",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "Dusun Mandiri",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/113 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "BENNY WINALDA",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "LINK. II BAHAGIA",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/114 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Budi Pratama",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "Dusun II",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/115 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Dewi",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "JL. WONOSARI DESA PAYA MABAR kec. STABAT KAB. LANG",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/116 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Eka Suwirza",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "JL. S. PARMAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/117 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Fahrozi",
        "-",
        "Penjaga Sekolah",
        "-",
        "",
        "Jln. D. I. Pandjaitan Lingk. I",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/118 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "0739759660300092",
        "Friska Mangunsong",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "JL. SM. RAJA DUSUN II NO.44",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/119 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4738753654300052",
        "Kristine Rosalin Valentina Sinaga",
        "197604062014072006",
        "Tenaga Administrasi Sekolah",
        "-",
        "II/a",
        "JL. SETIA LINGK. IV STABAT",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/120 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "M. RIDWAN",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "DUSUN XI ULU BRAYUN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/121 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "8148766667300043",
        "Maya Agustina",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "JLN. WARUKIN PO. 451 P. BRANDAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/122 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "NURSALIMAH",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "DUSUN III B CAMBAHAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/123 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "4146748651200053",
        "Paijo",
        "197008142014071002",
        "Tenaga Administrasi Sekolah",
        "-",
        "III/a",
        "LINGK. V ASMARA KW BINGAI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/124 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "2557748653200003",
        "Saiful Effendi",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "KW. BINGAI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/125 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Sulis Sutiono",
        "-",
        "Laboran",
        "-",
        "",
        "JL. KARYA BHAKTI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/126 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "1143747650200053",
        "Sutejo Ageng",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "JL. R. SUPRAPTO KW. BINGAI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/127 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "Tri Diana Syahri",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "LINGK. VIII BANTENAN",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/128 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "TRIA ELANDA",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "DUSUN VIII SUKA DAMAI",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/129 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
    [
        "-",
        "VENNY SHINTIA NASRI",
        "-",
        "Tenaga Administrasi Sekolah",
        "-",
        "",
        "JLN. S. PARMAN Gg. KURNIA",
        '<a href=https://www.smknegeri1stabat.sch.id/Surat/Guru/130 target="_blank"><i class="fa fa-eye"> </i> detail </a>',
    ],
];
let json = [];

json = teachers.map((teacher) => {
    return {
        nuptk: teacher[0],
        name: teacher[1],
        nip: teacher[2],
        jenis_ptk: teacher[3],
        tugas_tambahan: teacher[4],
        golongan: teacher[5],
        address: teacher[6],
    };
});

console.log(json);
